### ISSUE TITLE
Export overwrites everything in webapp without warning

### ISSUE THREAD

**Issue by kayceegb** [Offerel/SyncMarks-Extension#21]
Hi,

We talked about this one yesterday. It is the case in ext from amo and in dev branch. 

That should be easy, there is a message for import. 

K.

**Comment by Offerel** [comment]
Fixed with commit [fa12358](https://github.com/Offerel/SyncMarks-Extension/commit/fa123580ad9bb9df25f9934c0a237f22748f8386)

**Comment by kayceegb** [comment]
Tested. The confirmation is there but now after the export there is a prompt "what should firefox do with this file ? (open/save/...)

**Comment by kayceegb** [comment]
And, for the information, the prompt is also opened for import. ( I had this one for a futur issue)

**Comment by Offerel** [comment]
I have searched the net and installed the a little bit ancient FF60ESR for testing, but i couldnt reproduce the open/save dialog issue. The open/save dialog is only used, when you try to save the logfile from options page. Also the changelog.md is displayed correctly in his tab.

**Comment by kayceegb** [comment]
Ah ! I have a test environment since this morning with FF 78.5.0esr and I still have this behaviour :/ I don't know what to try else.

**Comment by Offerel** [comment]
Are there any other addons or maybe entry in prefs.js? Maybe some GPO policys? I don't know if GPO's exists, with this behavior. I have only no other ideas.

**Comment by kayceegb** [comment]
I have this with a new/clean/fresh profile for FF 78.5.0esr, only xpi signature set to false. No GPOs at all i'm on a linux environment. 

What puzzles me is that before you added the confirmation for export, the prompt was not there for export (already been there for import). 

From my research, it may be related to file content type management. What is your configuration in FF for .md files ?

**Comment by Offerel** [comment]
I have no special configuration for md files inside of FF. At OS level, they have also no association. I use markdown a lot but only inside of apps like Typora and others. 

The only difference is the OS. I'm mostly at Windows 10. Currently I use Linux only at server level.

But changelog and saving the logfile is the only place where I deal with local files. Import and export queries only the browser db and send the results via http request to the server. There should be no open/save dialog for that.

**Comment by kayceegb** [comment]
I maybe have an explanation for why it's appearing in import/export. 

When you open addon's preferences it tries to open the changelog. When you confirm import/export, I have the impression that the addon's preferences are reopened, so it want to get changelog again. :/ 

And about md files, I have no problem opening them in firefox. I can open this https://raw.githubusercontent.com/Offerel/SyncMarks-Extension/master/CHANGELOG.md and FF shows me directly the text context.
